name: Build and Deploy to Minikube

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Start Minikube
      shell: powershell
      run: |
        Write-Output "Checking Minikube status..."
        $status = minikube status
        if ($status -notmatch "Running") {
          Write-Output "Starting Minikube..."
          minikube start
        }

    - name: Set up Docker environment for Minikube
      shell: powershell
      run: |
        Write-Output "Setting Docker env for Minikube"
        $envScript = minikube -p minikube docker-env --shell powershell
        Invoke-Expression $envScript

    - name: Build frontend image
      shell: powershell
      run: docker build -t badarfaisal98/scdfrontend:latest ./client

    - name: Build backend image
      shell: powershell
      run: docker build -t badarfaisal98/scdbackend:latest ./server

    - name: Docker Hub Login
      shell: powershell
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push frontend image
      shell: powershell
      run: docker push badarfaisal98/scdfrontend:latest

    - name: Push backend image
      shell: powershell
      run: docker push badarfaisal98/scdbackend:latest

    - name: Deploy to Minikube
      shell: powershell
      run: |
        Write-Output "Applying Kubernetes configurations..."
        kubectl apply -f k8s/client-deployment.yaml
        kubectl apply -f k8s/server-deployment.yaml
        kubectl apply -f k8s/client-service.yaml
        kubectl apply -f k8s/server-service.yaml
