name: Build and Deploy to Minikube

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Start Minikube
      shell: powershell
      run: |
        Write-Output "Checking Minikube status..."
        $status = minikube status
        if ($status -notmatch "Running") {
          Write-Output "Starting Minikube..."
          minikube start
        }

    - name: Build frontend image
      shell: powershell
      run: |
        Write-Output "Building frontend Docker image..."
        docker build -t scdfrontend:latest ./client

    - name: Build backend image
      shell: powershell
      run: |
        Write-Output "Building backend Docker image..."
        docker build -t scdbackend:latest ./server

    - name: Load images into Minikube
      shell: powershell
      run: |
        Write-Output "Loading frontend image into Minikube..."
        minikube image load scdfrontend:latest
        Write-Output "Loading backend image into Minikube..."
        minikube image load scdbackend:latest

    - name: Deploy to Minikube
      shell: powershell
      run: |
        Write-Output "Applying Kubernetes manifests..."
        kubectl apply -f k8s/client-deployment.yaml
        kubectl apply -f k8s/server-deployment.yaml
        kubectl apply -f k8s/client-service.yaml
        kubectl apply -f k8s/server-service.yaml
